# Generated by Django 4.2.4 on 2023-08-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bootcamps', '0003_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
