# Generated by Django 4.2.4 on 2023-08-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bootcamps', '0004_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
